### ISSUE TITLE
launcher_profiles.json

### ISSUE THREAD

**Issue by MrSrsen** [TheSprtCz/-RG-Installer#1]
Instalátor síce prepíše pôvodný súbor ale prepíše ho zlým (starým) spôsobom a zmeny sa po spustený launcheru zmažú do defaultu. Pomôže len manuálne vytvorenie nových profilov.

<img width="1280" alt="instalator" src="https://cloud.githubusercontent.com/assets/13176514/15808284/18488cf4-2b74-11e6-91ba-0306cc0d80ad.png">

**Comment by pehala** [comment]
Opraveno, díky za nahlášení :-)
